spring.application.name=interview
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

jwt.issuer=smartmock-interview
jwt.accessTtlMinutes=10
jwt.refreshTtlDays=14
jwt.secret=${JWT_SECRET}

auth.refreshCookieName=refresh_token
auth.refreshCookiePath=/auth/refresh
auth.cookieSecure=false
auth.sameSite=Lax